### PR TITLE
Protect routes

### LINKED ISSUE #81: FE: protect routes
When a user is not signed in, they can still type a path in the browser and navigate to `/rooms` and enter a room.

We should protect authenticated routes so that users that are not signed in are always redirected to `/signIn`. The only non-authenticated routes should be `/signIn` and `/signUp`.

I think [this blog](https://ui.dev/react-router-protected-routes-authentication) shows how to do it.

### PR DESCRIPTION
**Pull request by marcovidonis**
Fixes #81.

### CODE REVIEW

**Comment by marcovidonis** [comment]
Technically this works, but is a bit broken by the fact that it all relies on the user info in store, and this is lost whenever the page is refreshed or when navigating to a page by typing the route in the browser.

We need to persist that information to make this work as expected.

**Comment by ghbogarin** [comment]
@marcovidonis I've just opened a PR that handles data persistence: https://github.com/montevideo-tech/hybrid-meetup-platform/pull/106

**Comment by marcovidonis** [comment]
Fixed, now it works with the persistent state.

Users that are not logged in cannot navigate to the following protected routes:
- `/rooms`
- `/rooms/:roomId`
- `/rooms/:roomId/edit`

They will be redirected to `/signIn`.

Logged in users cannot navigate to `/signIn` or `/signUp` and will be redirected to `/rooms`.

**Comment by marcovidonis** [comment]
@mpollingerQualabs this PR is ready. Could you take a look before we merge it?

**Pull request merged**
