### PR TITLE
Sort remote participants according to their priority 

### LINKED ISSUE #141: Change the name of the platform in multiple places
Image
Change the tab title to Hybridly.

Image
Change the header title to Hybridly

### LINKED ISSUE #142: SUBTASK: Implement a priority queue for rendering the remoteParticipants
Create a priority queue to store the remoteParticipants information.
We are probably gonna need some way to show all the participants ordered by priority to render them.

### LINKED ISSUE #143: SUBTASK: Prioritize participants that are currently speaking
In the priority queue participants that are currently speaking should have the highest priority.
This must be the highest type of priority.

### PR DESCRIPTION
**Pull request by fpyoung**
Fix #142 
Fix #143

### CODE REVIEW

**Review by marcovidonis — APPROVED** [review]
LGTM. Do you have a short video or gif showing it in action?

**Comment by fpyoung** [comment]
ezgif com-video-to-gif (1)

**Comment by marcovidonis** [comment]
Thanks! It feels a bit jumpy, so perhaps we might think about including a timer or some other strategy to delay the update. But that could be a separate ticket :)

**Comment by fpyoung** [comment]
yes I had the same thought! I wanted to try adding another condition before to see how it looks like, I'll create the PR with the other condtion #140 to see if it gets better and attatch a GIF again. 
If it still looks jumpy I'll create a ticket for that.

**Pull request merged**
