### PR TITLE
Add Mux Spaces wrapper

### LINKED ISSUE #14: Mux Spaces wrapper
We're going to build an abstraction layer on top of the WebRTC providers.

By default, Mux provides this ‘Automatic Subscription Mode’ where it automatically subscribes you to the 20 most active remote participants, as determined by its own logic in the server side. However, you can also initialise the Space in Manual Mode like so:
```js
// Initialize Space using Manual mode
const space = new Space(JWT, {
    subscriptionMode: SubscriptionMode.Manual,
});
```

Which is what we’ll need to do, because we want compatibility with other services. So we’ll be handling subscription and scalability manually, TBD how – easiest thing initially would be to subscribe to all new participants based on ‘participant joined’ event like so:
```js
space.on(SpaceEvent.ParticipantJoined, (participant) => { });
```

EDIT: updated table

#### Preliminary map of classes and methods

Reference: [Mux docs](https://devdocs.mux.com/spaces-web/latest/modules.html)
| **Our platform (Front-End)** | **Mux Spaces-web** |
| --- | --- |
| **Room** | **Space** |
| *Methods* |
| Room.join() | Space.join() |
| Room.leave() | Space.leave() |
| *Parameters* |
| Room.remoteParticipants | Space.participants |
| Room.id | Space.spaceId |
| *Events* |
| ParticipantJoined | ParticipantJoined |
| ParticipantLeft | ParticipantLeft |
||
| **LocalParticipant** | **LocalParticipant** |
| *Methods* |
| LocalParticipant.getTracks() | LocalParticipant.getTracks() |
| LocalParticipant.publishTracks() | LocalParticipant.publishTracks() |
| LocalParticipant.unpublishTracks() | LocalParticipant.unpublishTracks() |
| LocalParticipant.unpublishAllTracks() | LocalParticipant.unpublishAllTracks() |
| LocalParticipant.updateTracks() | LocalParticipant.updateTracks() |
| *Parameters* |
| LocalParticipant.id | LocalParticipant.connectionId *(TBC)* |
| LocalParticipant.displayName | LocalParticipant.id *(TBC)* |
| LocalParticipant.role | LocalParticipant.role |
| LocalParticipant.tracks | – |
| *Events* |
| StartedSpeaking | StartedSpeaking |
| StoppedSpeaking | StoppedSpeaking |
||
| **RemoteParticipant** | **RemoteParticipant** |
| *Methods* |
| RemoteParticipant.getTracks() | RemoteParticipant.getTracks() |
| RemoteParticipant.subscribe () | RemoteParticipant.subscribe () |
| RemoteParticipant.unsubscribe () | RemoteParticipant.unsubscribe () |
| *Parameters* |
| RemoteParticipant.id | RemoteParticipant.connectionId *(TBC)* |
| RemoteParticipant.displayName | RemoteParticipant.id *(TBC)* |
| RemoteParticipant.role | RemoteParticipant.role |
| RemoteParticipant.tracks | – |
| *Events* |
| *See LocalParticipant events* |
||
| **Track** | **Track** |
| *Methods* |
| *TDB* |
| *Parameters* |
| Track.id | Track.id |
| Track.muted | Track.muted |
| *Events* |
| Muted | Muted |
| Unmuted | Unmuted |

### PR DESCRIPTION
**Pull request by marcovidonis**
Create a wrapper for WebRTC providers and include Mux Spaces, with the possibility of adding other providers in the future.

This will enable the web app to join a video call on Mux Spaces, providing all the relevant classes (Room, Participant, Track, etc).

Addresses #14.

### CODE REVIEW

**Comment by marcovidonis** [comment]
I made a small RoomTest component to test using our WebRTC library. It could also be used as an example to build the actual components we'll need.

**Comment by marcovidonis** [comment]
I think we're getting there.. just need to refine the events so that we used our wrapped components in the callback functions (currently the event will run the callback with Mux's classes, need to change that).

After that, I think the wrapper will be ready to use.

**Comment by marcovidonis** [comment]
I believe the wrapper is done now. I added a route to load the `RoomTest` component at `/room-test`. We'll probably want to remove it when we implement the actual `Room` component.

**Review by ghbogarin — APPROVED** [review]
Looks good to me!

**Pull request merged**
